application: reverewhatboundtodestroy
version: sprint8
runtime: python27
api_version: 1

default_expiration: "5d 12h"

threadsafe: false

libraries:
- name: numpy
  version: latest
- name: webapp2
  version: latest
- name: django
  version: "1.3"

handlers:
- url: /
  script: index.app
- url: /index.html
  script: index.py 

# All URLs beginning with /stylesheets are treated as paths to static files in
# the stylesheets/ directory. Note that static_dir handlers do not use a
# regular expression for the URL pattern, only a prefix.
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images

#file not found
- url: /.*
  script: file_not_found.py
